<?php

namespace App\Http\Requests\Master\PeriodeAktif;

use Illuminate\Foundation\Http\FormRequest;

class UpdatePeriodeAktifRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        if (auth()->check()) {
            return true;
        }
        return false;
    }

    /**
     * Get the validation rules that apply to the request.
     * //'unique:namatable,namakolom,valuerequest|required'
     * @return array
     */
    public function rules()
    {
        return [
            //'ID' => 'unique:Ms_PeriodeAktif,ID,'.$this->ID.',ID|required',
            'NamaPeriode' => 'required',
            'Tahun' => 'required',
            'StatusPeriode' => 'nullable',
            'Aktif' => 'nullable',
            'Keterangan' => 'nullable',
        ];
    }

    /**
     * @return array
     */
    public function messages()
    {
        return parent::messages(); // TODO: Change the autogenerated stub
    }
}
